spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/postgres
    username: postgres-one
    password: postgres-one
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
#    properties:
#      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
